from .driver import DriverBasicInfo, DriverTripCreateUpdateSerializer, DriverTripListRetrieveSerializer
from .passenger import BasicPassengerTripListRetrieveSerializer, DetailedPassengerTripListRetrieveSerializer, PassengerSerializer
from .actions import DriverActionsSerializer
