# Generated by Django 2.1.1 on 2018-10-13 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='destination',
            field=models.CharField(default='', max_length=500, verbose_name='Enderço de destino da carona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarm',
            name='origin',
            field=models.CharField(default='', max_length=500, verbose_name='Enderço de origem da carona'),
            preserve_default=False,
        ),
    ]
