# Generated by Django 2.1.2 on 2018-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_auto_20181013_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='price',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Preço máximo da carona em reais'),
        ),
    ]
