# Generated by Django 2.1.7 on 2019-03-15 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0004_auto_20181031_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='destination_radius',
            field=models.FloatField(default=10, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0.05)], verbose_name='Raio de pesquisa do destino em km'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='origin_radius',
            field=models.FloatField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.05)], verbose_name='Raio de pesquisa da origem em km'),
        ),
    ]
