# Generated by Django 2.1.1 on 2018-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_squashed_0009_auto_20180922_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='published_past',
            field=models.BooleanField(default=False, help_text='Whether or not the app has been published before'),
        ),
    ]
