# Generated by Django 2.0.3 on 2018-07-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20171218_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='plataform',
            new_name='platform',
        ),
    ]
