# Generated by Django 2.1.1 on 2018-10-06 04:39

from django.db import migrations
import project.validators
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_application_published_past'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=versatileimagefield.fields.VersatileImageField(upload_to='app_logos/', validators=[project.validators.MinImageDimensionsValidator(512, 512), project.validators.MaxImageDimensionsValidator(1024, 1024), project.validators.SquareImageValidator()], verbose_name="App's logo"),
        ),
    ]
