# Generated by Django 2.0.3 on 2018-07-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20180703_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_id',
        ),
    ]
