# Generated by Django 2.1.1 on 2018-09-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_remove_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='published',
            field=models.BooleanField(default=False, help_text='Whether or not your app is published'),
        ),
        migrations.AddField(
            model_name='application',
            name='website',
            field=models.TextField(blank=True, help_text="App's website or download page"),
        ),
    ]
