# Generated by Django 2.1.1 on 2018-10-10 04:07

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_application_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='webhook_url',
            field=models.URLField(blank=True, validators=[project.validators.CustomURLValidator()]),
        ),
    ]
