# Generated by Django 2.1.1 on 2018-09-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_auto_20180914_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(blank=True, help_text="App's website or download page"),
        ),
    ]
