# Generated by Django 2.1.1 on 2018-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_auto_20180914_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.URLField(blank=True),
        ),
    ]
