# Generated by Django 2.1.1 on 2018-09-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_application_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-id']},
        ),
    ]
