# Generated by Django 2.1.1 on 2018-10-18 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0009_pkcegrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkcegrant',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(43)]),
        ),
        migrations.AlterField(
            model_name='pkcegrant',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
