# Generated by Django 2.1.1 on 2018-10-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0010_auto_20181018_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkcegrant',
            name='code_challenge_method',
            field=models.CharField(blank=True, choices=[('plain', 'plain'), ('S256', 'S256')], max_length=10),
        ),
    ]
