# Generated by Django 2.1.1 on 2018-10-19 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0011_auto_20181018_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkcegrant',
            name='code_challenge',
            field=models.CharField(blank=True, default='', max_length=128, validators=[django.core.validators.MinLengthValidator(43)]),
        ),
        migrations.AlterField(
            model_name='pkcegrant',
            name='code_challenge_method',
            field=models.CharField(blank=True, choices=[('plain', 'plain'), ('S256', 'S256')], default='', max_length=10),
        ),
    ]
