# Generated by Django 2.1.1 on 2018-09-10 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('car_color', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes_animals', models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')])),
                ('likes_smoking', models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')])),
                ('likes_music', models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro'), ('na', 'Prefiro não dizer')], max_length=10)),
                ('phone', models.CharField(help_text='Usado para contato', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('unicamp', 'Unicamp')], max_length=100)),
                ('university_email', models.EmailField(max_length=100)),
                ('university_id', models.CharField(max_length=30)),
                ('enroll_year', models.IntegerField(help_text='Ano que você entrou na universidade', validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1998)])),
                ('course', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
