# Generated by Django 2.1.1 on 2018-10-01 07:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=50, verbose_name='Marca do carro')),
                ('car_model', models.CharField(max_length=50, verbose_name='Modelo do carro')),
                ('car_color', models.CharField(max_length=30, verbose_name='Cor do carro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes_music', models.IntegerField(choices=[(0, 'Curto silêncio'), (1, 'Depende da música'), (2, 'Adoro música!')], default=0, verbose_name='Curte música')),
                ('likes_smoking', models.IntegerField(choices=[(0, 'Cigarro não, por favor'), (1, 'Às vezes permito fumar'), (2, 'Cigarro não me incomoda')], default=0, verbose_name='Curte fumar')),
                ('likes_pets', models.IntegerField(choices=[(0, 'Animais não, por favor'), (1, 'Depende do animal'), (2, 'Adoro animais!')], default=0, verbose_name='Curte animais de estimação')),
                ('likes_talking', models.IntegerField(choices=[(0, 'Gosto de paisagens'), (1, 'Às vezes curto conversar'), (2, 'Adoro conversar!')], default=0, verbose_name='Curte conversar')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Data de aniversário')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro'), ('na', 'Prefiro não dizer')], max_length=10, verbose_name='Gênero')),
                ('phone', models.CharField(help_text='Usado para contato', max_length=20, verbose_name='Celular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(choices=[('unicamp', 'Unicamp')], max_length=100, verbose_name='Sua universidades')),
                ('university_email', models.EmailField(max_length=100, verbose_name='Email acadêmico')),
                ('university_id', models.CharField(max_length=30, verbose_name='ID acadêmica (RA, etc)')),
                ('enroll_year', models.IntegerField(help_text='Ano que você entrou na universidade', validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1998)], verbose_name='Ano de ingresso')),
                ('course', models.CharField(max_length=100, verbose_name='Curso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates_notifications', models.BooleanField(default=True, verbose_name='Atualizações em caronas e alarmes')),
                ('ratings_notifications', models.BooleanField(default=True, verbose_name='Avaliações feitas para você')),
                ('news_notifications', models.BooleanField(default=True, verbose_name='Novidades e notícias do Unicaronas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
