# Generated by Django 2.1.1 on 2018-10-01 15:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_squashed_0006_auto_20180919_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Usado para contato', max_length=128, verbose_name='Celular'),
        ),
    ]
