# Generated by Django 2.1.1 on 2018-09-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_preferences_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='likes_animals',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')], default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='likes_music',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')], default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='likes_smoking',
            field=models.IntegerField(choices=[(0, 'Não'), (1, 'Um pouco'), (2, 'Sim')], default=0),
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
    ]
