# Generated by Django 2.1.1 on 2018-10-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20181001_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='likes_music',
            field=models.CharField(blank=True, choices=[('Curto silêncio', 'Curto silêncio'), ('Depende da música', 'Depende da música'), ('Adoro música!', 'Adoro música!')], max_length=30, verbose_name='Curte música'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='likes_pets',
            field=models.CharField(blank=True, choices=[('Animais não, por favor', 'Animais não, por favor'), ('Depende do animal', 'Depende do animal'), ('Adoro animais!', 'Adoro animais!')], max_length=30, verbose_name='Curte animais de estimação'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='likes_smoking',
            field=models.CharField(blank=True, choices=[('Cigarro não, por favor', 'Cigarro não, por favor'), ('Às vezes permito fumar', 'Às vezes permito fumar'), ('Cigarro não me incomoda', 'Cigarro não me incomoda')], max_length=30, verbose_name='Curte fumar'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='likes_talking',
            field=models.CharField(blank=True, choices=[('Gosto de paisagens', 'Gosto de paisagens'), ('Às vezes curto conversar', 'Às vezes curto conversar'), ('Adoro conversar!', 'Adoro conversar!')], max_length=30, verbose_name='Curte conversar'),
        ),
    ]
