# Generated by Django 2.1.2 on 2018-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_auto_20181006_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp'), ('pucc', 'PUC-Campinas'), ('usp', 'USP')], max_length=100, verbose_name='Sua universidades'),
        ),
    ]
