# Generated by Django 2.1.1 on 2018-09-18 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_auto_20180917_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='likes_animals',
        ),
        migrations.AddField(
            model_name='driver',
            name='likes_pets',
            field=models.IntegerField(choices=[(0, 'Animais não, por favor'), (1, 'Depende do animal'), (2, 'Adoro animais!')], default=0, verbose_name='Curte animais de estimação'),
        ),
        migrations.AddField(
            model_name='driver',
            name='likes_talking',
            field=models.IntegerField(choices=[(0, 'Gosto de paisagens'), (1, 'Às vezes curto conversar'), (2, 'Adoro conversar!')], default=0, verbose_name='Curte conversar'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_color',
            field=models.CharField(max_length=30, verbose_name='Cor do carro'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_make',
            field=models.CharField(max_length=50, verbose_name='Marca do carro'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_model',
            field=models.CharField(max_length=50, verbose_name='Modelo do carro'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='likes_music',
            field=models.IntegerField(choices=[(0, 'Curto silêncio'), (1, 'Depende da música'), (2, 'Adoro música!')], default=0, verbose_name='Curte música'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='likes_smoking',
            field=models.IntegerField(choices=[(0, 'Cigarro não, por favor'), (1, 'Às vezes permito fumar'), (2, 'Cigarro não me incomoda')], default=0, verbose_name='Curte fumar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(verbose_name='Data de aniversário'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('other', 'Outro'), ('na', 'Prefiro não dizer')], max_length=10, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Usado para contato', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_year',
            field=models.IntegerField(help_text='Ano que você entrou na universidade', validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1998)], verbose_name='Ano de ingresso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp')], max_length=100, verbose_name='Sua universidades'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_email',
            field=models.EmailField(max_length=100, verbose_name='Email acadêmico'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university_id',
            field=models.CharField(max_length=30, verbose_name='ID acadêmica (RA, etc)'),
        ),
    ]
