# Generated by Django 2.1.7 on 2019-03-15 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_auto_20181115_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll_year',
            field=models.IntegerField(help_text='Ano que você entrou na universidade', validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1999)], verbose_name='Ano de ingresso'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp'), ('pucc', 'PUC-Campinas'), ('usp', 'USP'), ('ifsp', 'IFSP')], max_length=100, verbose_name='Sua universidades'),
        ),
    ]
