# Generated by Django 2.1.1 on 2018-09-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='news_notifications',
            field=models.BooleanField(default=True, verbose_name='Novidades e notícias do Unicaronas'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='ratings_notifications',
            field=models.BooleanField(default=True, verbose_name='Avaliações feitas para você'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='updates_notifications',
            field=models.BooleanField(default=True, verbose_name='Atualizações em caronas e alarmes'),
        ),
    ]
