# Generated by Django 2.1.7 on 2019-03-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0005_auto_20190315_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Seu nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Seu email para contato')),
                ('university_name', models.CharField(max_length=50, verbose_name='Nome ou sigla da universidade/faculdade')),
                ('university_id', models.CharField(max_length=50, verbose_name='ID acadêmica (RA, etc)')),
                ('university_email', models.EmailField(max_length=254, verbose_name='Email acadêmico')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp'), ('usp', 'USP'), ('unesp', 'Unesp'), ('unifesp', 'Unifesp'), ('pucc', 'PUC-Campinas'), ('ifsp', 'IFSP')], max_length=100, verbose_name='Sua universidades'),
        ),
    ]
