# Generated by Django 2.1.7 on 2019-03-25 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_auto_20190319_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enroll_year',
            field=models.IntegerField(help_text='Ano que você entrou na universidade', validators=[django.core.validators.MinValueValidator(1994)], verbose_name='Ano de ingresso'),
        ),
    ]
