# Generated by Django 2.1.7 on 2019-04-02 02:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_auto_20190325_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to=user_data.models.filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('contact_email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('denied', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp'), ('usp', 'USP'), ('unesp', 'Unesp'), ('unifesp', 'Unifesp'), ('pucc', 'PUC-Campinas'), ('ifsp', 'IFSP'), ('facamp', 'FACAMP')], max_length=100, verbose_name='Sua universidades'),
        ),
        migrations.AddField(
            model_name='studentproof',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_data.Student'),
        ),
    ]
