# Generated by Django 2.1.7 on 2019-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_auto_20190401_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentproof',
            name='denied',
        ),
        migrations.AddField(
            model_name='studentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('denied', 'Negado')], default='pending', max_length=20),
        ),
    ]
