# Generated by Django 2.1.7 on 2019-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_studentproof_proof_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(choices=[('unicamp', 'Unicamp'), ('usp', 'USP'), ('unesp', 'Unesp'), ('unifesp', 'Unifesp'), ('facamp', 'FACAMP'), ('pucc', 'PUC-Campinas'), ('ifsp', 'IFSP')], max_length=30, verbose_name='Sua universidades'),
        ),
    ]
