# Generated by Django 2.1.1 on 2018-10-01 07:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import search.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100, verbose_name='Pesquisa original')),
                ('address', models.TextField(max_length=200, verbose_name='Enderço completo da pesquisa')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordenadas da pesquisa')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data de adesão da pesquisa')),
                ('expires', models.DateTimeField(default=search.models.get_default_expire)),
            ],
        ),
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path_info', models.CharField(max_length=200)),
                ('full_path_info', models.TextField()),
                ('method', models.CharField(max_length=10)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_hits', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='search.DBResult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_hits', to=settings.AUTH_USER_MODEL)),
                ('query_type', models.CharField(default='origin', max_length=20)),
            ],
        ),
    ]
