# Generated by Django 2.1.1 on 2018-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_squashed_0003_auto_20180929_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='query_type',
            field=models.CharField(max_length=20),
        ),
    ]
