# Generated by Django 2.1.1 on 2018-09-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_hit_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='full_path_info',
            field=models.TextField(),
        ),
    ]
