# Generated by Django 2.1.2 on 2018-11-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181001_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbresult',
            name='query',
            field=models.CharField(max_length=500, verbose_name='Pesquisa original'),
        ),
    ]
