# Generated by Django 2.1.7 on 2019-03-15 22:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20181102_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbresult',
            name='address_components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True, verbose_name='Componentes do endereço'),
        ),
    ]
