# Generated by Django 2.1.1 on 2018-10-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookgroup',
            name='group_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
