# Generated by Django 2.1.1 on 2018-09-22 22:05

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('denied', 'denied')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=200, verbose_name='Enderço de origem da carona')),
                ('origin_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordenadas de origem da carona')),
                ('destination', models.CharField(max_length=200, verbose_name='Enderço de destino da carona')),
                ('destination_point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Coordenadas de destino da carona')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Preço da carona em reais')),
                ('datetime', models.DateTimeField(verbose_name='Datetime de saída da carona')),
                ('max_seats', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Máximo número de assentos na carona')),
                ('auto_approve', models.BooleanField(default=True, verbose_name='Auto aprovação de passageiros')),
                ('details', models.TextField(verbose_name='Detalhes fornecidos pelo motorista')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_offered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='trips.Trip'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
