# Generated by Django 2.1.1 on 2018-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='details',
            field=models.TextField(blank=True, verbose_name='Detalhes fornecidos pelo motorista'),
        ),
    ]
