# Generated by Django 2.1.2 on 2018-11-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_squashed_0005_auto_20180929_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de assentos reservados'),
        ),
    ]
