# Generated by Django 2.1.7 on 2019-03-15 22:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_passenger_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_address_components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True, verbose_name='Componentes do endereço de origem'),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_address_components',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True, verbose_name='Componentes do endereço de origem'),
        ),
    ]
