# Generated by Django 2.1.1 on 2018-09-24 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180923_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='book_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Hora que o passageiro fez a reserva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='auto_approve',
            field=models.BooleanField(default=True, verbose_name='Aprovação automática de passageiros'),
        ),
    ]
