# Generated by Django 2.1.7 on 2019-04-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20190315_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='facebook_post_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
