# Generated by Django 2.1.1 on 2018-09-25 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('trips', '0003_auto_20180924_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trips', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
