# Generated by Django 2.1.1 on 2018-09-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=500, verbose_name='Enderço de destino da carona'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(max_length=500, verbose_name='Enderço de origem da carona'),
        ),
    ]
